############################################################
# +------------------------------------------------------+ #
# |                     GGFeaturesREL                    | #
# +------------------------------------------------------+ #
############################################################

# This is the config file for GGFeaturesREL.
# This config was generated for version 4.0.

# If you want to use special characters in this document, such as accented letters, you MUST save the file as UTF-8, not ANSI.
# If you receive an error when Essentials loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
#   - You have "escaped" all apostrophes in your text: If you want to write "don't", for example, write "don''t" instead (note the doubled apostrophe)
#   - Text with symbols is enclosed in single or double quotation marks

# If you need help make sure to join the Nikunity Discord Server:

############################################################
# +------------------------------------------------------+ #
# |               GGFeaturesREL (Global)                 | #
# +------------------------------------------------------+ #
############################################################

GGFeatures:
  Settings:

    Prefix: '&7[&4&lGGFeatures&6REL&7] &r'

    AdOnJoin: true